### PR TITLE
Use production API of syncano by default

### PR DESCRIPTION
**Pull request by ilonajulczuk**

### CODE REVIEW

**Comment by ilonajulczuk** [comment]
@dczlonka could you take a look at tests? Why they fail? I would like to make it possible to use production version of syncano from library.

**Comment by dczlonka** [comment]
@ilonajulczuk after re-test, everything went ok. I'm not able to check what was wrong.

Only log I found:

> Test failed to run to completion. Reason: 'Instrumentation run failed due to 'junit.framework.AssertionFailedError''. Check device logcat for details

**Comment by dczlonka** [comment]
I've made another test (this time on proper branch). Tests failed because something was not found.

> HTTP Response: 404  NOT FOUND
> I think instance is missing.

**Comment by MariuszWisniewski** [comment]
We already have API link changed now, closing.

**Pull request closed without merging**
